/**
 * Canonical cycle data types for the Olanna Health app.
 *
 * These types define the shared vocabulary between:
 *   - cycleProfileService (storage/retrieval of the user's baseline profile)
 *   - cycleCalculator (pure prediction math)
 *   - cycleUtils (utilities for late detection, calendar markers, etc.)
 *   - useLotusCycle / useCalendarCycle hooks (React hooks consumed by screens)
 *
 * The app uses two parallel phase naming conventions:
 *   - CyclePhase: Title-case strings ("Menstrual", "Follicular", "Ovulatory", "Luteal")
 *     used in the public/canonical cycle API and displayed in the UI.
 *   - Phase: Lowercase internal strings ("menstrual", "follicular", "ovulation", "luteal", "late")
 *     used by phaseConfig.ts, the cycle wheel, and phase-specific color/content lookups.
 *
 * Mapping helpers toInternalPhase() and toCyclePhase() convert between the two.
 */
import { Phase } from "@/constants/phaseConfig";

export type { Phase };

/**
 * Public-facing cycle phase names displayed in the UI.
 * Includes the four standard phases plus "Late Luteal" which activates
 * when the expected period date has passed with no new bleed logged.
 */
export type CyclePhase =
  | "Menstrual"
  | "Follicular"
  | "Ovulatory"
  | "Luteal"
  | "Late Luteal";

/**
 * The user's baseline cycle profile — the single source of truth
 * for cycle predictions until actual logged data overrides it.
 *
 * Populated during onboarding and persisted via cycleProfileService.
 * Fields:
 *   userId               - Unique identifier matching the UserProfile.id
 *   lastPeriodStartDate  - ISO date string (YYYY-MM-DD) of the most recent period start
 *   averageCycleLength   - Average number of days in a full cycle (default 28)
 *   averagePeriodLength  - Average number of days of menstrual flow (default 5)
 *   onboardingSymptoms   - Optional health conditions selected during onboarding (e.g. PCOS)
 *   onboardingPreferences - Optional user preferences collected during onboarding
 *   updatedAt            - ISO timestamp of last profile update
 */
export interface CycleProfile {
  userId: string;
  lastPeriodStartDate: string; // YYYY-MM-DD
  averageCycleLength: number;
  averagePeriodLength: number;
  onboardingSymptoms?: string[];
  onboardingPreferences?: string[];
  updatedAt: string;
}

/**
 * A user-logged actual cycle event that overrides prediction data.
 * When the user logs a real period start date, it takes precedence
 * over the onboarding baseline for future predictions.
 *
 * Fields:
 *   id              - Unique identifier for this log entry
 *   userId          - The user who logged this event
 *   periodStartDate - ISO date string (YYYY-MM-DD) of the actual period start
 *   createdAt       - ISO timestamp of when this was logged
 */
export interface CycleLog {
  id: string;
  userId: string;
  periodStartDate: string; // actual logged date
  createdAt: string;
}

/**
 * Full cycle prediction computed from a CycleProfile.
 * Generated by cycleCalculator.generateCyclePrediction().
 *
 * Contains everything the UI needs to display current cycle state
 * and future predictions on both the Lotus and Calendar screens.
 */
export interface CyclePrediction {
  /** Current day in the cycle (1-indexed, wraps via modulo for past cycles) */
  currentCycleDay: number;
  /** Raw (unwrapped) cycle day — continues counting past cycleLength (e.g. Day 37) */
  rawCycleDay: number;
  /** True when rawCycleDay exceeds averageCycleLength and no new period logged */
  isLate: boolean;
  /** Number of days past the expected cycle length (0 if not late) */
  daysLate: number;
  /** ISO date of the expected period start (lastPeriodStart + cycleLength) */
  expectedPeriodDate: string;
  /** True when the expected period date is 0–2 days away */
  isPeriodDueSoon: boolean;
  /** The phase corresponding to the current cycle day */
  currentPhase: CyclePhase;
  /** ISO date string of the predicted next period start */
  nextPeriodStartDate: string;
  /** ISO date string marking the start of the fertile window */
  fertileWindowStart: string;
  /** ISO date string marking the end of the fertile window */
  fertileWindowEnd: string;
  /** ISO date string of the predicted ovulation day */
  ovulationDate: string;
  /** Array of ISO date strings for predicted next period days */
  periodDates: string[];
  /** Phase ranges with start/end dates for the current cycle */
  phaseRanges: {
    phase: CyclePhase;
    start: string;
    end: string;
  }[];
  /** Human-readable phase label for display (e.g. "Late Luteal Phase") */
  uiLabel: string;
  /** Contextual status message (e.g. "Your period is 8 days late.") */
  message: string;
  /** Supporting guidance text (e.g. "You remain in the luteal phase until a new bleed is logged.") */
  helperText: string;
}

/**
 * Marker data for a single day in the calendar grid.
 * Generated by cycleUtils.generateCalendarMarkers().
 * Combines prediction data with actual flow logs for display.
 */
export interface CalendarDayMarker {
  day: number;
  dateKey: string;
  dayInCycle: number;
  phase: CyclePhase;
  /** True if this day has a logged flow OR falls within predicted period */
  isPeriod: boolean;
  /** True if this day falls within the predicted fertile window */
  isFertile: boolean;
  /** True if this is the predicted ovulation day */
  isOvulation: boolean;
  /** True if this day falls within the PMS window (last 7 days of cycle) */
  isPMS: boolean;
  isToday: boolean;
  /** True if the user has manually logged flow data for this day */
  hasFlowLog: boolean;
}

/**
 * Minimal flow log entry used by cycle utilities.
 * Represents a single day's flow data from the user's daily logs.
 */
export interface FlowLog {
  date: string;
  flow?: string | null;
}

/**
 * Mapping from public CyclePhase to internal Phase.
 * Note: "Ovulatory" maps to "ovulation" (internal convention).
 */
const PHASE_TO_INTERNAL: Record<CyclePhase, Phase> = {
  Menstrual: "menstrual",
  Follicular: "follicular",
  Ovulatory: "ovulation",
  Luteal: "luteal",
  "Late Luteal": "late",
};

const INTERNAL_TO_PHASE: Record<string, CyclePhase> = {
  menstrual: "Menstrual",
  follicular: "Follicular",
  ovulation: "Ovulatory",
  luteal: "Luteal",
  late: "Late Luteal",
};

/** Convert a public CyclePhase to the internal Phase used by phaseConfig. */
export function toInternalPhase(cp: CyclePhase): Phase {
  return PHASE_TO_INTERNAL[cp];
}

/** Convert an internal Phase to the public CyclePhase used in the UI. */
export function toCyclePhase(p: Phase): CyclePhase {
  return INTERNAL_TO_PHASE[p] ?? "Follicular";
}
