export const Spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  "2xl": 40,
  "3xl": 48,
  "4xl": 56,
  inputHeight: 52,
  buttonHeight: 52,
} as const;

export const BorderRadius = {
  sm: 4,
  md: 8,
  lg: 16,
  xl: 24,
  full: 999,
} as const;

export const Fonts = {
  heading: "Poppins_600SemiBold",
  headingMedium: "Poppins_500Medium",
  headingLight: "Poppins_400Regular",
  body: "Poppins_300Light",
  bodyMedium: "Poppins_400Regular",
  bodySemibold: "Poppins_500Medium",
  numeric: "Poppins_400Regular",
  numericBold: "Poppins_600SemiBold",
  light: "Poppins_300Light",
} as const;

export const Typography = {
  h1: {
    fontFamily: Fonts.heading,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: "600" as const,
    letterSpacing: -0.5,
  },
  h2: {
    fontFamily: Fonts.headingMedium,
    fontSize: 22,
    lineHeight: 30,
    fontWeight: "500" as const,
    letterSpacing: -0.3,
  },
  h3: {
    fontFamily: Fonts.headingLight,
    fontSize: 18,
    lineHeight: 26,
    fontWeight: "400" as const,
  },
  h4: {
    fontFamily: Fonts.bodyMedium,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: "400" as const,
  },
  body: {
    fontFamily: Fonts.body,
    fontSize: 15,
    lineHeight: 24,
    letterSpacing: 0.1,
  },
  small: {
    fontFamily: Fonts.body,
    fontSize: 13,
    lineHeight: 20,
    letterSpacing: 0.1,
  },
  caption: {
    fontFamily: Fonts.light,
    fontSize: 12,
    lineHeight: 18,
    letterSpacing: 0.2,
  },
  button: {
    fontFamily: Fonts.bodySemibold,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: "500" as const,
    letterSpacing: 0.5,
  },
  numeric: {
    fontFamily: Fonts.numeric,
    fontSize: 15,
    lineHeight: 22,
  },
  numericLarge: {
    fontFamily: Fonts.numericBold,
    fontSize: 32,
    lineHeight: 40,
    letterSpacing: -0.5,
  },
  link: {
    fontFamily: Fonts.body,
    fontSize: 15,
    lineHeight: 24,
  },
} as const;

export const Shadows = {
  soft: {
    shadowColor: "#2A2420",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  glow: {
    shadowColor: "#E8C4B8",
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 3,
  },
  sm: {
    shadowColor: "#2A2420",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  md: {
    shadowColor: "#2A2420",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.04,
    shadowRadius: 6,
    elevation: 2,
  },
  lg: {
    shadowColor: "#2A2420",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.06,
    shadowRadius: 12,
    elevation: 3,
  },
} as const;

const VogueColors = {
  cream: "#FAF6F3",
  warmWhite: "#FFFCFA",
  blush: "#F5E1DC",
  blushLight: "#FAF0ED",
  blushMuted: "#E8CFC8",
  taupe: "#C4B5AD",
  taupeLight: "#DDD4CF",
  taupeDark: "#9A8B82",
  charcoal: "#3A3530",
  warmGray: "#6B635C",
  softPink: "#E8C4B8",
  dustyRose: "#D4A99A",
  sand: "#E5DDD8",
  sandLight: "#F0EBE8",
  ivory: "#F8F4F1",
  espresso: "#2A2420",
  sage: "#B8C4B8",
  sageLight: "#D0DCD0",
  sageMuted: "#A0ADA0",
  gold: "#C9A86C",
  goldLight: "#DBC498",
  goldMuted: "#B8956A",
  lavender: "#C8C0D0",
  lavenderLight: "#DDD8E5",
  lavenderMuted: "#B0A8B8",
  terracotta: "#D4A090",
  terracottaLight: "#E8C8C0",
  terracottaMuted: "#C08878",
  logoPink: "#FEC8EE",
  logoPinkLight: "#FFDDF5",
  logoPinkDark: "#F8A5D8",
  periodPink: "#F472B6",
  periodPinkLight: "#FBCFE8",
  fertileCoral: "#FB923C",
  fertileCoralLight: "#FED7AA",
  pmsLavender: "#A78BFA",
  pmsLavenderLight: "#DDD6FE",
};

export const PhaseColors = {
  menstrual: {
    primary: VogueColors.terracotta,
    light: VogueColors.terracottaLight,
    dark: VogueColors.terracottaMuted,
    name: "Menstrual",
    lotusState: "closed",
    mood: "Rest & Release",
  },
  follicular: {
    primary: VogueColors.sage,
    light: VogueColors.sageLight,
    dark: VogueColors.sageMuted,
    name: "Follicular",
    lotusState: "rising",
    mood: "Renewal",
  },
  ovulation: {
    primary: VogueColors.gold,
    light: VogueColors.goldLight,
    dark: VogueColors.goldMuted,
    name: "Ovulation",
    lotusState: "bloom",
    mood: "Radiance",
  },
  luteal: {
    primary: VogueColors.lavender,
    light: VogueColors.lavenderLight,
    dark: VogueColors.lavenderMuted,
    name: "Luteal",
    lotusState: "closing",
    mood: "Reflection",
  },
};

export const SemanticColors = {
  neutral: VogueColors.cream,
  action: VogueColors.dustyRose,
  insight: VogueColors.gold,
  pain: VogueColors.terracotta,
  calm: VogueColors.sage,
  reflection: VogueColors.lavender,
  textPrimary: VogueColors.charcoal,
  textSecondary: VogueColors.warmGray,
};

export const ThemePresets = {
  olanna: {
    name: "Olanna",
    primary: VogueColors.dustyRose,
    secondary: VogueColors.taupe,
    tertiary: VogueColors.lavender,
    accent: VogueColors.gold,
    phaseMenstrual: VogueColors.terracotta,
    phaseFollicular: VogueColors.sage,
    phaseOvulation: VogueColors.gold,
    phaseLuteal: VogueColors.lavender,
  },
  blossom: {
    name: "Blossom",
    primary: VogueColors.softPink,
    secondary: VogueColors.lavender,
    tertiary: VogueColors.taupe,
    accent: VogueColors.sage,
    phaseMenstrual: VogueColors.terracotta,
    phaseFollicular: VogueColors.sage,
    phaseOvulation: VogueColors.gold,
    phaseLuteal: VogueColors.lavender,
  },
  garden: {
    name: "Garden",
    primary: VogueColors.sage,
    secondary: VogueColors.dustyRose,
    tertiary: VogueColors.gold,
    accent: VogueColors.lavender,
    phaseMenstrual: VogueColors.terracotta,
    phaseFollicular: VogueColors.sage,
    phaseOvulation: VogueColors.gold,
    phaseLuteal: VogueColors.lavender,
  },
  dreamy: {
    name: "Dreamy",
    primary: VogueColors.lavender,
    secondary: VogueColors.dustyRose,
    tertiary: VogueColors.sage,
    accent: VogueColors.gold,
    phaseMenstrual: VogueColors.terracottaLight,
    phaseFollicular: VogueColors.sageLight,
    phaseOvulation: VogueColors.goldLight,
    phaseLuteal: VogueColors.lavenderLight,
  },
};

export const Colors = {
  light: {
    text: VogueColors.charcoal,
    textSecondary: VogueColors.warmGray,
    background: VogueColors.cream,
    backgroundRoot: VogueColors.cream,
    backgroundDefault: VogueColors.warmWhite,
    backgroundSecondary: VogueColors.sandLight,
    border: VogueColors.sand,
    tint: VogueColors.dustyRose,

    primary: VogueColors.logoPink,
    primaryLight: VogueColors.logoPinkLight,
    primaryDark: VogueColors.logoPinkDark,
    secondary: VogueColors.taupe,
    secondaryLight: VogueColors.taupeLight,
    tertiary: VogueColors.lavender,
    tertiaryLight: VogueColors.lavenderLight,
    accent: VogueColors.gold,
    accentLight: VogueColors.goldLight,

    phaseMenstrual: VogueColors.terracotta,
    phaseFollicular: VogueColors.sage,
    phaseOvulation: VogueColors.gold,
    phaseLuteal: VogueColors.lavender,

    success: VogueColors.sage,
    warning: VogueColors.gold,
    error: VogueColors.terracotta,
    info: VogueColors.lavender,

    tabIconDefault: VogueColors.taupe,
    tabIconSelected: VogueColors.logoPink,

    buttonText: VogueColors.warmWhite,
    buttonSecondaryText: VogueColors.charcoal,

    cardBackground: VogueColors.warmWhite,
    cardBorder: VogueColors.sand,

    lotusCenter: VogueColors.gold,
    lotusPetal: VogueColors.dustyRose,
    lotusGlow: "rgba(212, 169, 154, 0.2)",
    lotusGoldGlow: "rgba(201, 168, 108, 0.15)",
    waterRipple: "rgba(184, 196, 184, 0.15)",

    link: VogueColors.dustyRose,

    insightGold: VogueColors.gold,
    calmSage: VogueColors.sage,
    moodLavender: VogueColors.lavender,
    painTerracotta: VogueColors.terracotta,

    logoPink: VogueColors.logoPink,
    logoPinkLight: VogueColors.logoPinkLight,
    periodPink: VogueColors.periodPink,
    periodPinkLight: VogueColors.periodPinkLight,
    fertileCoral: VogueColors.fertileCoral,
    fertileCoralLight: VogueColors.fertileCoralLight,
    pmsLavender: VogueColors.pmsLavender,
    pmsLavenderLight: VogueColors.pmsLavenderLight,
  },
  dark: {
    text: VogueColors.charcoal,
    textSecondary: VogueColors.warmGray,
    background: VogueColors.cream,
    backgroundRoot: VogueColors.cream,
    backgroundDefault: VogueColors.warmWhite,
    backgroundSecondary: VogueColors.sandLight,
    border: VogueColors.sand,
    tint: VogueColors.dustyRose,

    primary: VogueColors.logoPink,
    primaryLight: VogueColors.logoPinkLight,
    primaryDark: VogueColors.logoPinkDark,
    secondary: VogueColors.taupe,
    secondaryLight: VogueColors.taupeLight,
    tertiary: VogueColors.lavender,
    tertiaryLight: VogueColors.lavenderLight,
    accent: VogueColors.gold,
    accentLight: VogueColors.goldLight,

    phaseMenstrual: VogueColors.terracotta,
    phaseFollicular: VogueColors.sage,
    phaseOvulation: VogueColors.gold,
    phaseLuteal: VogueColors.lavender,

    success: VogueColors.sage,
    warning: VogueColors.gold,
    error: VogueColors.terracotta,
    info: VogueColors.lavender,

    tabIconDefault: VogueColors.taupe,
    tabIconSelected: VogueColors.logoPink,

    buttonText: VogueColors.warmWhite,
    buttonSecondaryText: VogueColors.charcoal,

    cardBackground: VogueColors.warmWhite,
    cardBorder: VogueColors.sand,

    lotusCenter: VogueColors.gold,
    lotusPetal: VogueColors.dustyRose,
    lotusGlow: "rgba(212, 169, 154, 0.2)",
    lotusGoldGlow: "rgba(201, 168, 108, 0.15)",
    waterRipple: "rgba(184, 196, 184, 0.15)",

    link: VogueColors.dustyRose,

    insightGold: VogueColors.gold,
    calmSage: VogueColors.sage,
    moodLavender: VogueColors.lavender,
    painTerracotta: VogueColors.terracotta,

    logoPink: VogueColors.logoPink,
    logoPinkLight: VogueColors.logoPinkLight,
    periodPink: VogueColors.periodPink,
    periodPinkLight: VogueColors.periodPinkLight,
    fertileCoral: VogueColors.fertileCoral,
    fertileCoralLight: VogueColors.fertileCoralLight,
    pmsLavender: VogueColors.pmsLavender,
    pmsLavenderLight: VogueColors.pmsLavenderLight,
  },
};
